###
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Bolgo",
    "email":"mongo@gmail.com",
    "password":"123456",
    "date_created":"2022/01/20"
}

###

GET http://localhost:5000/api/users HTTP/1.1

###
GET http://localhost:5000/api/users/63cb0c500a36473aa9c2ef90 HTTP/1.1

###
PUT  http://localhost:5000/api/users/63cb0c500a36473aa9c2ef90 HTTP/1.1
Content-Type: application/json

{
    "name":"Nikola",
    "email":"mongo@gmail.com",
    "password":"123456",
    "date_created":"2022/01/20"
}

###
DELETE http://localhost:5000/api/users/1 HTTP/1.1
###
GET http://localhost:5000/api/shows HTTP/1.1
###
GET http://localhost:5000/api/shows/Drama HTTP/1.1
###
GET http://api.tvmaze.com/shows/1 HTTP/1.1